# Makefile.host -- native (Linux) build of the server core, for tests.
CC      ?= cc
CFLAGS  ?= -O2 -g -Wall -Wextra -Wno-unused-parameter -DZSTD_DISABLE_ASM
CPPFLAGS += -I../protocol \
            -I../third_party/zstd \
            -I../third_party/zstd/common \
            -I../third_party/zstd/decompress \
            -I../third_party/lzma

SERVER_SRC := main-linux.c stream_server.c io.c decode.c decode_zstd.c \
              decode_lzma.c
ZSTD_SRC   := $(wildcard ../third_party/zstd/common/*.c) \
              $(wildcard ../third_party/zstd/decompress/*.c)
LZMA_SRC   := ../third_party/lzma/LzmaDec.c \
              ../third_party/lzma/Lzma2Dec.c \
              ../third_party/lzma/CpuArch.c

BIN := server-native

all: $(BIN)

$(BIN): $(SERVER_SRC) $(ZSTD_SRC) $(LZMA_SRC)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ $^

clean:
	rm -f $(BIN)

.PHONY: all clean
